language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

jobs:
  include:
    - stage: deploy
      script: skip
      if: env(deploy) IS present
      deploy:
        provider: script
        script: sh deploy.sh

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - git clone https://github.com/smartsheet-platform/smartsheet-sdk-tests.git
  - smartsheet-sdk-tests/travis_scripts/install_wiremock.sh

install:
  - pip install --upgrade pip
  - pip install certifi
  - pip install enum34 requests six python-dateutil coverage coveralls[yaml] pytest pytest-travis-fold pytest-instafail requests-toolbelt

script:
  - smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
  - coverage run --source=smartsheet setup.py test

after_success:
  - coveralls --verbose
